%YAML:1.0
dataPath: "./darknet_cfg/coco.data"
netCfgPath: "./darknet_cfg/yolo.cfg"
weightPath: "./darknet_cfg/yolo.weights"
nameListPath: "./darknet_cfg/coco.names"
alphabetPath: "./darknet_cfg/labels/"
imgPathFile: "./KITTI_slam_cfg/imagePath.txt"
saveVideo: "./robotcar2015-11-11-14-13-43.avi"
nClass: 6
thresh: 0.50
hier_thresh: 0.5
nms: 0.4
